# Mémoire maximale allouée à Gradle (1 Go suffit pour ce petit projet et sauve votre RAM)
org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8

# Activer le cache pour accélérer les prochaines compilations
org.gradle.caching=true
org.gradle.parallel=true

# Configuration Android
android.useAndroidX=true
android.enableJetifier=true